# Python Modules
import numpy as np

# Local Modules
from lowpolypainter.color import Color

# TODO: Add better function to insert new faces
# TODO: Delete vertecies or faces one by one

"""
Mesh Class

Description:
Stores mesh of vertices, which connections are stored as faces.
Points and tris can be added and removed from the mesh.
"""

class Mesh(object):

    def __init__(self, width, height):
        self.faces = []
        self.vertices = []
        self.width = width
        self.height = height

    # Adds vertex to mesh
    def addVertex(self, x, y):
        self.vertices.append(Vertex(x, y))

        # Improvised generate faces for testing
        # Faces are generated by last two vertices in vertices array + new vertex
        if (len(self.vertices) >= 3):
            verticesLast = len(self.vertices)
            self.addFace(verticesLast - 3 ,
                         verticesLast - 2,
                         verticesLast - 1,
                         Color.random())

    # Adds face to mesh
    def addFace(self, vertexIndex1, vertexIndex2, vertexIndex3, color):
        face = Face(vertexIndex1, vertexIndex2, vertexIndex3, color)
        self.faces.append(face)

    # Adds random number off vertecies
    # TODO: Remove and create init veticies
    def addRandomVerticies(self, count):
        # Random points
        for index in range(count):
            x = np.random.randint(self.width)
            y = np.random.randint(self.height)
            self.addVertex(x, y)


    # Deletes all vertecies and faces
    def clear(self):
        self.faces = []
        self.vertices = []


"""
Vertex Class

Description:
Stores a vertex of the mesh, which contains and x and y coordinate.
"""

class Vertex(object):

    def __init__(self, x, y):
        self.x = x
        self.y = y


"""
Face Class

Description:
Stores faces of the mesh, which contains three vertecies and a color.
"""

class Face(object):

    def __init__(self, vertexPos1, vertexPos2, vertexPos3, color):
        self.vertices = [vertexPos1, vertexPos2, vertexPos3]
        self.color = color
